Fix directory in approval script.

diff --git a/approve b/approve
--- a/approve
+++ b/approve
@@ -29,7 +29,7 @@ tsc $declarationFiles --out /dev/null
 # elm make --docs=documentation.json
 
 echo 'Confirming that generated code is unchanged...'
-git diff --exit-code -- 'tests-approval/expectSuccess/**/*.d.ts' || (echo 'FAILURE' && echo 'examples code has changed. Commit changes to approve.' && exit 1)
+git diff --exit-code -- './**/*.d.ts' || (echo 'FAILURE' && echo 'examples code has changed. Commit changes to approve.' && exit 1)
 
 
 echo 'RUNNING ERROR CASES...'
