Move test_data folder.

diff --git a/approve b/approve
--- a/approve
+++ b/approve
@@ -5,26 +5,29 @@ echo BASH_VERSION $BASH_VERSION
 set -o errexit
 
 npm run build
-binary=../../bin/elm-typescript-interop
+projectRoot=`pwd`
+binary=$projectRoot/bin/elm-typescript-interop
 
-for testFolder in ./test_data/*
+cd tests/approval/expectSuccess
+
+for testFolder in *
 do
   echo "Testing generator with $testFolder folder"
   cd $testFolder
-  outputBase=`basename $testFolder`
+  # outputBase=`basename $testFolder`
   # outputPath=../../tests/e2e/output/$outputBase.d.ts
   $binary src/Main.elm
-  cd ../..
+  cd -
 done
 
 echo "Checking that all TypeScript declaration files are valid..."
-declarationFiles=$(find test_data -type f -name "*.d.ts")
+declarationFiles=$(find . -type f -name "*.d.ts")
 tsc $declarationFiles --out /dev/null
 
 # echo 'Ensuring documentation is valid...'
 # elm make --docs=documentation.json
 
 echo 'Confirming that generated code is unchanged...'
-git diff --exit-code -- 'test_data/**/*.d.ts' || (echo 'FAILURE' && echo 'examples code has changed. Commit changes to approve.' && exit 1)
+git diff --exit-code -- 'tests/approval/expectSuccess/**/*.d.ts' || (echo 'FAILURE' && echo 'examples code has changed. Commit changes to approve.' && exit 1)
 
 echo 'SUCCESS'
